### PR TITLE
Implementation of IsoformSwitchAnalyzeR

### PR DESCRIPTION
**Pull request by jesseangelis**
## Description of changes

In reference to issue  #148

Dear rnasplice team, as my colleague discussed with you on slack on 15 February, I have added IsoformSwitchAnalyseR to the pipeline.

IsoformSwitchAnalyzeR is a powerful tool for identifying isoform switches in transcript data.

IsoformSwitchAnalyzeR takes a Salmon results directory as input. If it finds genes with isoform switches, it produces publication-quality plots visualising these switches. A separate set of switch plots is generated for each contrast if that contrast contains significant switches. Two .csv files are also created, a summary and the main data frame. The .rds of the main R-list is also returned.
This results in the following file structure:

isoformswitchanalyzer
|-- results
|         |-- Condition1_vs_Condition2
|         |                        |-- 01_switch_plot_gene1.pdf
|         |                        |-- 02_switch_plot_gene2.pdf
|         |                        |-- 03_switch_plot_gene3.pdf
|         |                        
|         |-- Condition2_vs_Condition3
|         |                       |-- 01_switch_plot_gene4.pdf
|         |                       |-- 02_switch_plot_gene5.pdf
|         |                       |-- 03_switch_plot_gene6.pdf
|
|-- isoformswitchanalyzer_isoformfeatures.csv
|
|-- isoformswitchanalyzer_summary.csv
|
|-- switchlist.rds

## Details

A new local module was added calling an R script in bin. 
The module is called from the rnasplice workflow.
A new test for IsoformSwitchAnalyzeR was added.
Documentation, config scripts, etc. were updated according to the guidelines. 

Some of the commits are from merges with the updated master branch. 

The lint checks failed. But they also failed before I implemented the changes.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/rnasplice/tree/master/.github/CONTRIBUTING.md)
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jma1991** [comment]
Hi Jesse,

Thank you so much for submitting a pull request for IsoformSwitchAnalyzerR!

I’ve added myself along with two other maintainers to help review it.

@bensouthgate, if you’ve got a moment, could you take a look?
@lathikaa, could you or someone from the bioinformatics team also give it a review when possible?

Thanks again for your contribution!

Best regards,
James

**Comment by jma1991** [comment]
@lathikaa Can you also replicate the changes to the metro-map which Jesse has committed using the original Canva template?

**Comment by jesseangelis** [comment]
@bensouthgate 
@lathikaa 
@jma1991 

Hi  everyone, the code review has been pending for a while now. Is there anything I can help you with to get it started? 
Best regard,
Jesse

**Comment by lathikaa** [comment]
Hi @jesseangelis , 
Apologies for the delay. We've tested the code, and everything is looking good so far. Just a few final steps and the metro map need to be updated. We'll have it merged soon. Sorry that it's taking a bit longer than expected, but we're almost there!

Thanks, 
Lathika

**Comment by jesseangelis** [comment]
@lathikaa 
Sounds good! Is there anything I can help you with?

**Review by lathikaa — APPROVED** [review]

**Comment by lathikaa** [comment]
@jesseangelis We need to make updates to remove the lib folder to ensure that nf-core linting passes, enabling us to merge into the dev branch. We're currently reviewing the necessary changes to accomplish this.

**Comment by lathikaa** [comment]
Hi @jesseangelis,
Apologies for the delay.
Thanks again for your contribution! It is now merged to dev :)

Regards, 
Lathika

**Comment by jesseangelis** [comment]
@lathikaa Perfect, thank you!

**Pull request merged**
